Math upgrades
jellypbc/poster pull request #322
Opened 2020-10-08 06:39 UTC by cindywu

- [x] for inline-math show katex-render in tooltip and katex-editor inline
- [ ] for block-math show-katex render below katex-editor

2020-10-08 06:40 UTC, cindywu commented
![Kapture 2020-10-07 at 20 40 07](https://user-images.githubusercontent.com/1177031/95423766-5c0bbd80-08dd-11eb-88ef-78984030419b.gif)

2020-10-22 21:18 UTC, dennyluan requested changes

2020-10-22 21:18 UTC, dennyluan commented on app/assets/stylesheets/editor/math.scss
> +  .ProseMirror {
smell: can fix this to just be explicit like the other lines

2020-10-22 21:18 UTC, dennyluan commented on app/assets/stylesheets/editor/math.scss
> +  .ProseMirror {
e.g. `math.math-inline.ProseMirror-selectednode {`

2020-10-22 21:18 UTC, dennyluan commented on app/javascript/components/PostEditor.js
> +      <div className="post-editor-container">
why is this being added?

2021-02-05 04:55 UTC, cindywu commented
Closing this PR. We are migrating to Typescript https://github.com/jellypbc/poster/pull/404, so I will restart this PR to avoid the mess.

2021-02-05 04:55 UTC, closed without merging